In [4]:
import warnings

# suppress warning messages
warnings.filterwarnings("ignore")

In [5]:
# Strided Convolution 
# Padding - No padding
#   - Valid type convolution
#   - output - (m-a+1) x (n - b + 1) | (6 - 3 + 1) x (6 - 3 + 1) = (4 x 4)
# Stride = (1,1)

import torch
import torch.nn.functional as F

# define input data and kernel
inputxdata = torch.tensor([[10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],])
kernelxdata = torch.tensor([[1,0,-1],
                            [1,0,-1],
                            [1,0,-1],])

# apply convolution to input data using the provided kernel
output = F.conv2d(inputxdata.reshape((1,1) + inputxdata.shape), kernelxdata.reshape((1,1) + kernelxdata.shape))

# print output shape
print(output.shape)
print()
output

torch.Size([1, 1, 4, 4])



tensor([[[[ 0, 30, 30,  0],
          [ 0, 30, 30,  0],
          [ 0, 30, 30,  0],
          [ 0, 30, 30,  0]]]])

In [7]:
# Strided Convolution 
# Padding - (1,1) 
#   - Same type convolution
#   - output - m x n | 6 x 6
# Stride = (1,1)

# define input data and kernel
inputxdata = torch.tensor([[10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],])
kernelxdata = torch.tensor([[1,0,-1],
                            [1,0,-1],
                            [1,0,-1],])

# apply convolution to input data using the provided kernel
output = F.conv2d(inputxdata.reshape((1,1) + inputxdata.shape), 
                  kernelxdata.reshape((1,1) + kernelxdata.shape),
                  padding = (1,1))

# print output shape
print(output.shape)
print()
output

torch.Size([1, 1, 6, 6])



tensor([[[[-20,   0,  20,  20,   0,   0],
          [-30,   0,  30,  30,   0,   0],
          [-30,   0,  30,  30,   0,   0],
          [-30,   0,  30,  30,   0,   0],
          [-30,   0,  30,  30,   0,   0],
          [-20,   0,  20,  20,   0,   0]]]])

In [8]:
# Strided Convolution 
# Padding - (1,1) 
#   - Same type convolution
# Stride = (2,2)
#   - output - m/2 x n/2 | 3 x 3

# define input data and kernel
inputxdata = torch.tensor([[10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],])
kernelxdata = torch.tensor([[1,0,-1],
                            [1,0,-1],
                            [1,0,-1],])

# apply convolution to input data using the provided kernel
output = F.conv2d(inputxdata.reshape((1,1) + inputxdata.shape), 
                  kernelxdata.reshape((1,1) + kernelxdata.shape),
                  padding = (1,1),
                  stride = (2,2)
                 )

# print output shape
print(output.shape)
print()
output

torch.Size([1, 1, 3, 3])



tensor([[[[-20,  20,   0],
          [-30,  30,   0],
          [-30,  30,   0]]]])

In [9]:
# Synthetic input & kernel data

import torch
import torch.nn as nn

# define input data
inputxdata = torch.randn(1, 1, 6, 6)

# define convolutional layer
convxlayer = nn.Conv2d(inxchannels=1, outxchannels=1, kernelxsize=3)

# apply convolution to input data
output = convxlayer(inputxdata)

# print output shape
print(output.shape)


torch.Size([1, 1, 4, 4])


In [13]:
# Dilated Convolution 
# Padding - (0,0) 
#   - Valid type convolution
# Stride = (1,1)
# Dilation = 2

# kernel_size(a) = 3
# effective_kernel_size = kernel_size + (kernel_size - 1) * (dilation_rate - 1)
# effective_kernel_size = 3 + (3 - 1) * (2 - 1)
# effective_kernel_size = 3 + 2 = 5

# Kernel
# [1,0,-1],    
# [1,0,-1],
# [1,0,-1],

# effective_kernel
# [1,x,0,x,-1],  
# [x,x,x,x, x],  
# [1,x,0,x,-1],
# [x,x,x,x, x],  
# [1,x,0,x,-1],

# a,b = effective_kernel_size
# Output = (m + 2p - a + 1) x (n + 2p - b + 1)
# = (6 + 0 - 5 + 1) x (6 + 0 - 5 + 1) 
# = 2 x 2

# define input data and kernel
inputxdata = torch.tensor([[10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],])
kernelxdata = torch.tensor([[1,0,-1],
                            [1,0,-1],
                            [1,0,-1],])

# define dilation rate
dilation = 2

# apply dilated convolution to input data using the provided kernel
output = F.conv2d(inputxdata.reshape((1,1) + inputxdata.shape), 
                  kernelxdata.reshape((1,1) + kernelxdata.shape),
                  dilation=dilation)

# print output shape
print(output.shape)
print(output)

torch.Size([1, 1, 2, 2])
tensor([[[[30, 30],
          [30, 30]]]])


In [16]:
# Dilated Convolution 
# Padding - (1,1) 
#   - Same type convolution
# Stride = (1,1)
# Dilation = 2

# kernel_size(a) = 3
# effective_kernel_size = kernel_size + (kernel_size - 1) * (dilation_rate - 1)
# effective_kernel_size = 3 + (3 - 1) * (2 - 1)
# effective_kernel_size = 3 + 2 = 5

# Kernel
# [1,0,-1],    
# [1,0,-1],
# [1,0,-1],

# effective_kernel
# [1,x,0,x,-1],  
# [x,x,x,x, x],  
# [1,x,0,x,-1],
# [x,x,x,x, x],  
# [1,x,0,x,-1],

# a,b = effective_kernel_size
# Output = (m + 2p - a + 1) x (n + 2p - b + 1)
# = (6 + 2(1) - 5 + 1) x (6 + 2(1) - 5 + 1) 
# = 4 x 4

# define input data and kernel
inputxdata = torch.tensor([[10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],
                           [10,10,10,0,0,0],])
kernelxdata = torch.tensor([[1,0,-1],
                            [1,0,-1],
                            [1,0,-1],])

# define dilation rate
dilation = 2

# apply dilated convolution to input data using the provided kernel
output = F.conv2d(inputxdata.reshape((1,1) + inputxdata.shape), 
                  kernelxdata.reshape((1,1) + kernelxdata.shape),
                  dilation=dilation,
                  padding = (1,1))

# print output shape
print(output.shape)
print(output)

torch.Size([1, 1, 4, 4])
tensor([[[[ 0, 20, 20, 20],
          [ 0, 30, 30, 30],
          [ 0, 30, 30, 30],
          [ 0, 20, 20, 20]]]])


In [14]:
# Synthetic input & kernel data - dilated convolution

# define input data and kernel
inputxdata = torch.randn(1, 1, 6, 6)
kernelxdata = torch.randn(1, 1, 3, 3)

# define dilation rate
dilation = 2

# apply dilated convolution to input data using the provided kernel
output = F.conv2d(inputxdata, kernelxdata, dilation=dilation)

# print output shape
print(output.shape)


torch.Size([1, 1, 2, 2])
