In [6]:
# Generating Data for Linear Regression
import numpy as np

x = np.array(list(range(2,20,2))).reshape(-1,1)
y = np.array(list(range(4,40,4))).reshape(-1,1)

In [14]:
from sklearn.linear_model import LinearRegression

m = LinearRegression()

m.fit(x,y)

# Coeff. of Determination / R2 score
m.score(x,y)

1.0

In [15]:
m.intercept_

array([-3.55271368e-15])

In [16]:
m.coef_

array([[2.]])

In [21]:
m.predict(np.array(7,).reshape(-1,1))

array([[14.]])

In [ ]:
|